#!/system/bin/sh

chmod 777 /proc/sys/kernel/random/read_wakeup_threshold
echo "1366" > /proc/sys/kernel/random/read_wakeup_threshold
chmod 777 /proc/sys/kernel/random/write_wakeup_threshold
echo "2048" > /proc/sys/kernel/random/write_wakeup_threshold

chmod 755 /sys/devices/system/cpu/sched_mc_power_savings
echo "2" > /sys/devices/system/cpu/sched_mc_power_savings

chmod 775 /sys/module/lowmemorykiller/parameters/minfree
chmod 775 /sys/module/lowmemorykiller/parameters/debug_level
chmod 775 /sys/module/lowmemorykiller/parameters/cost

echo "2048,16384,64000,76800,89600,102400" > /sys/module/lowmemorykiller/parameters/minfree
echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
echo "64" > /sys/module/lowmemorykiller/parameters/cost

chmod 644 /sys/module/lowmemorykiller/parameters/minfree
chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
chmod 644 /sys/module/lowmemorykiller/parameters/cost

echo "512" > /sys/devices/virtual/bdi/0:23/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:0/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:1/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:2/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:3/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:4/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:5/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:6/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:7/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:8/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:9/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:10/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:11/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:12/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:13/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:14/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/1:15/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:0/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:1/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:2/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:3/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:4/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:5/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:6/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/7:7/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/254:0/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/254:1/read_ahead_kb
echo "512" > /sys/devices/virtual/bdi/default/read_ahead_kb
